### ISSUE TITLE
Get build to work with either gmake or regular make

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#218]
We'd like to get the build to work with either GNU-make or regular make. There are some things I took from the CESM example build that require GNU make.

**Comment by ekluzek** [comment]
It looks like the problem is that both PIO and mpi-serial create Makefile's that require GNU Make. This would be problematic to support having them create both a regular Make and a GNU Make version.

**Comment by ekluzek** [comment]
One way around this would be to have a check that ensures you are using a valid version of GNU Make otherwise it would abort. We'll have to look into how to do that.

**Comment by nmizukami** [comment]
it seems like both GNU-make and regular make work.   I close this for now

**Comment by nmizukami** [comment]
It seems that both gmak and make work.
