### ISSUE TITLE
Add internal checks & corrections for topology

### ISSUE THREAD

**Issue by wknoben** [ESCOMP/mizuRoute#221]
I ran into an issue where some river segments in my domain shapefile have length 0 and this leads to a mizuRoute error:
```
 FATAL ERROR: init_data/init_ntopo/check_river_properties/reach length for reach id 74030207 is negative:   0.000000
```
I briefly discussed this with @ShervanGharari and he suggested to set the reach length in such cases to 1 m, so that mizuRoute can continue. I will be implementing this as a pre-processing step for my own work, but we thought it may be helpful to suggest this as a possible enhancement for future mizuRoute versions. 

This could take the form of a warning + correction, so that the user is aware that their input topology has been (slightly) changed but the run can still complete.

**Comment by nmizukami** [comment]
check+correction for unphysical reach length has been implemented (zero or negative length is replaced with 100 meter), and give a user a warning that suggest the user should look into these reach eventually.
