### ISSUE TITLE
Remove <varname_pfafCode> in the control file for parallel mizuRoute

### ISSUE THREAD

**Issue by tgq14** [ESCOMP/mizuRoute#224]
Parallel run of mizuRoute does not necessarily need <varname_pfafCode>, while the code still requires that <varname_pfafCode> is included in the control file and the corresponding variable is included in the river network netcdf file. I need to make a fake pfafCode variable in the netcdf file to run parallel mizuRoute. A better solution is to remove <varname_pfafCode> or to loose the variable check.

**Comment by nmizukami** [comment]
thanks Guoqiang (@tgq14),  that is correct - pfafstetter code is not used any longer.  I thought I turned off this variable so you don't need to specify, but I will need to check.

**Comment by tgq14** [comment]
I am using the feature/mpi-pio branch in case this may make a difference.

**Comment by nmizukami** [comment]
the lates one is cesm-coupling branch now, but for this problem, it does not matter.

**Comment by nmizukami** [comment]
<varname_pfafCode> does not need to be specified in control file in cesm-coupling (feature/mpi-pio is merged into this) branch.  Also, pfafcode does not need to be included in network data. 

So I think this issue is resolved.
