### ISSUE TITLE
Known limitation, need to use the same number of MPI tasks on restart

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#228]
@nmizukami let me know that the same number of MPI tasks need to be used on restart as were used to create the restart file. Changing this also would take some effort. Since, this is not something normally needed we are going to leave this a known limitation.

For CESM testing this means that we expect ERP tests to fail. ERT tests should work however as they only change the number of threads.

**Comment by ekluzek** [comment]
We should add a check for this when reading the restart file and gracefully fail with an error message so that this issue is obvious to the user. This will also give a easy to spot error message if you happen to run an ERP test.

**Comment by ekluzek** [comment]
nNodes in globalData is the number of MPI tasks. This should be added to the restart file and then checked against nNodes to make sure they are the same. This should be added to write_restart_pio.f90. It'll need to define it and write it. On read it should read it into a temporary variable and then compare it to the global nNodes.

**Comment by ekluzek** [comment]
@nmizukami if this approach sounds good I can commit it directly to the cesm-coupling branch. If you'd like to review it I can create a PR for it. Let me know which sounds best.

**Comment by nmizukami** [comment]
Hi @ekluzek,  thank you for doing this. Yes, I will review it and then merge it.

**Comment by ekluzek** [comment]
This is fixed for our purposes.
