### ISSUE TITLE
Exact restart tests failing because the list of time constant fields is different

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#239]
Exact restart tests are failing because the list of time constant fields is different. For example the test ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default fails as follows...

PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default CREATE_NEWCASE
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default XML
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SETUP
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SHAREDLIB_BUILD time=10
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default MODEL_BUILD time=42
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SUBMIT
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default RUN time=269
FAIL ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default COMPARE_base_rest
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default GENERATE ctsm5.1.dev069.mizu
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default MEMLEAK insuffiencient data for memleak test
PASS ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default SHORT_TERM_ARCHIVER

with the TestStatus.log file showing the following issue...

```
SUMMARY of cprnc:
 A total number of    493 fields were compared
          of which      0 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of      4 fields could not be analyzed
 A total number of      0 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of     10 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files seem to be IDENTICAL
      (But note that there were differences in field lists just for time-constant fields.)


```

**Comment by ekluzek** [comment]
Other tests showing this:

FAIL       ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default                      COMPARE_base_rest
FAIL       ERS_D.nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default                COMPARE_base_rest
PEND       ERP.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default                 COMPARE_base_rest
FAIL       ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default                    COMPARE_base_rest
FAIL       ERS_D.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default                    COMPARE_base_rest
PEND       ERP.nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default               COMPARE_base_rest

**Comment by ekluzek** [comment]
OK, it looks like the problem is just that the xml variable BFBFLAG needs to be set to true.

**Comment by ekluzek** [comment]
This test still fails:

ERS_D.nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default

because BasinID and ReachID for the .nc.base history file are identically 0, while they are proper values for the .nc.rest file history file.

**Comment by nmizukami** [comment]
Yes, USGS network is special (two catchments are flowing into one river reach), which likely mess things up.  so history file is not correct?

**Comment by ekluzek** [comment]
Ahhh, OK, so we expect some problems with the USGS grid. Although I would think the problem you give is an issue for any simulation running with the USGS grid though right? Is there any specific type of thing that we should expect to fail with the USGS grid?

**Comment by ekluzek** [comment]
Yes, @nmizukami one of the history files is clearly screwed up in regard to BasinID and ReachID. But, it's not clear to me why that's the case. I think this is a different problem than the fact that it's a USGS grid, but I'm not sure.

**Comment by ekluzek** [comment]
OK, I saw this problem again (but going back to the original list of time constant fields is different for CLM). I think the problem is actually just that hist_mfilt is set to 5, rather than 1, like in CLM. This works for CLM since then it only compares the last file, rather than including the first one that has all the fields on it.

**Comment by ekluzek** [comment]
I also noticed this problem in PEM tests if they weren't at least 10 days in length.

**Comment by ekluzek** [comment]
I haven't been seeing the BasinID/ReachID issue anymore. And the restart tests are working when I set the file frequency to day.

**Comment by ekluzek** [comment]
This is fixed now
