### ISSUE TITLE
Restart issue for mpi-serial case detected by nag compiler

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#280]
There's an issue with mpi-serial for restart that the the nag compiler found. The restart fails in mpi_restart when it gets to the "size(global_ix_comm)" intrinsic function call, because global_ix_comm has not been allocated as comm_ntopo_data is not called for the serial case.

Here's the traceback that shows that issue:

> Completion(send) valueRuntime Error: /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/mpi_process.f90, line 679: ALLOCATABLE GLOBAL_IX_COMM is not currently allocated
> Program terminated by fatal error
> /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/mpi_process.f90, line 679: Error occurred in MPI_PROCESS:MPI_RESTART
> /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/src/init_model_data.f90, line 461: Called by INIT_MODEL_DATA:INIT_STATE_DATA
> /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/cpl/RtmMod.F90, line 235: Called by RTMMOD:ROUTE_INI
> /fs/cgd/data0/erik/ctsm_mizuroute/components/mizuRoute/route/build/cpl/nuopc/rof_comp_nuopc.F90, line 521: Called by ROF_COMP_NUOPC:INITIALIZEREALIZE
> /fs/cgd/data0/erik/ctsm_mizuroute/components/cmeps/cime_config/../cesm/driver/esmApp.F90, line 128: Called by ESMAPP
> =288 tag=1

One way around it is to prevent the call to mpi_restart with the following change:

``` fortran
diff --git a/route/build/src/init_model_data.f90 b/route/build/src/init_model_data.f90
index 8d45ecd..409464e 100644
--- a/route/build/src/init_model_data.f90
+++ b/route/build/src/init_model_data.f90
@@ -457,7 +457,7 @@ SUBROUTINE init_state_data(pid, nNodes, comm, ierr, message)
       TSEC(0)=T0+dt; TSEC(1)=T1+dt
     end if
 
-    if (nNodes>0) then
+    if (nNodes>1) then
       call mpi_restart(pid, nNodes, comm, iens, ierr, cmessage)
       if(ierr/=0)then; message=trim(message)//trim(cmessage); return; endif
     end if
```

That allows the case to run, but it fails the restart with the field rofImp_Forr_rofl showing different answers on restart.

>  RMS rofImp_Forr_rofl                 8.1208E+02            NORMALIZED  1.3086E+00

So possibly parts of mpi_restart should still be run for the mpi-serial case, but those parts should be extracted out and always run, while the MPI specific parts should remain in mpi_restart.

**Comment by ekluzek** [comment]
We talked about this with @nmizukami, he sees what needs to be done to fix this. Might be fairly easy to fix. Some part of the code will need to be done all of the time, and some part only under MPI. Or possibly could stop earlier for the serial case.  There could be a if statement similar to above that only happens when multiple tasks are being done.

**Comment by nmizukami** [comment]
Hi @ekluzek, I think I can fix this quickly.  I will do pull-request for this fix and would you be able to take a look? Also are you testing again if this fix the problem?

**Comment by nmizukami** [comment]
Hi @ekluzek, I tested pull-request #282 with stand-alone to be sure that this did not break anything. I have already merged this pull-request.  I forgot linking the pull-request to this issue, so this issue needs to be closed manually.  But before closing, would be good to test with nag compiler

**Comment by ekluzek** [comment]
@nmizukami I updated and the test that was failing now passes for me:

SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default

So I'd say this good to go!
