### ISSUE TITLE
CLM grid vs mizuRoute catchment

### ISSUE THREAD

**Issue by nmizukami** [ESCOMP/mizuRoute#301]
Hi @ekluzek, 

Some of CLM grid boxes (e.g., fv0.9x1.25) are not overlapped by any mizuRoute catchments along the coasts.  I wonder if this causes problem with the water balance when mizuRoute passes runoff to the ocean. 

This is images showing fv0.9x1.25 grid vs mizuRoute HDMA catchment (orange is land and grey is no-land, so ocean)

![Screen Shot 2022-08-11 at 11 24 48 AM](https://user-images.githubusercontent.com/5290615/184195558-02329528-9360-4aa8-a5ab-1c5d2e2da843.png)

**Comment by ekluzek** [comment]
Hmmm. Good question. Although CESM will realize that these are cells that are only partially covered by land. So runoff, will only be from the land part of it. The ocean part of the cells will come from the ATM and send precipitation direct to the ocean. If you look at one CTSM coastal land cell, I think the key is that the area covered by mizuRoute for that cell should be the same as what CTSM thinks the land area is. If they are the same that should be OK. If they are different that's where there might be problems. But, we should also see how MOSART and RTM handle this, and if they are just constructed to ensure the land area is the same. So I'm not completely sure about this either, but we should look into it.

**Comment by nmizukami** [comment]
Hi @ekluzek, I am also wondering if river model has to run over Antarctica and greenland??  which are missing in HDMA.....

**Comment by ekluzek** [comment]
I think this is an important issue here. There are three grids that are important in the coupled system for ROF (the ocean grid/mask, the CTSM grid, and the mizuRoute grid). The land mask is going to differ between each of these. The land mask in CTSM comes from the mapping of the ocean grid/mask to the CTSM grid. And that is going to determine where runoff is sent from CTSM to mizuRoute. The easy cases to think about are:

- CTSM grid is ocean, but mizuRoute is land -- this means runoff is zero, which mizuRoute handles fine
- CTSM grid is land, but mizuRoute is ocean -- this means runoff will bypass mizuRoute and be sent directly to ocean

The cases that we need to think more deeply about are the coastal regions where there's a mismatch.

**Comment by nmizukami** [comment]
One remaining question would be how coupler handle partial overlap between LND grid and ROF grid. MOSART case also happen to this. Normalize the partial fraction?  

But there is no need to do anything in ROF code.
