### ISSUE TITLE
TAB character in the configuration/setting files

### ISSUE THREAD

**Issue by kasra-keshavarz** [ESCOMP/mizuRoute#308]
The capability of reading TAB characters (in addition to space) in the configuration (or settings) would make it much easier for the users to edit them.

Just an enhancement idea!

**Comment by ShervanGharari** [comment]
Or at least warn the users that there are tabs in the control file and exit. Adding this capability, if possible, would be highly appreciated.

**Comment by nmizukami** [comment]
Ok, see if I can find a way to handle TAB in ascii reading.  My text editor (vim) in linux converts spaces when I press a tab, so i did not run into this before.

**Comment by ekluzek** [comment]
I like @ShervanGharari suggestion of dying if there are tab characters. One way to do this would be to add something like do a check for tabs within a string

if ( index( string, achar(9) ) > 0 )then
   call abort()
end if

achar converts an integer to the ASCII value of it and 9 happens to be a tab. So this should work. You should add a comment to say that though...
