### ISSUE TITLE
Code release version 

### ISSUE THREAD

**Issue by AlaBahrami** [ESCOMP/mizuRoute#334]
Hi  @nmizukami , 

I think it will be quite better to write the version of code while running the program. It is be quite useful to track which version the user is using. This can be added to the main_route source code from launching the program. 

Thanks, 
Ala

**Comment by nmizukami** [comment]
Thank you for suggestion! Yes, will write it in history netcdf and printing on screen.

**Comment by nmizukami** [comment]
model version, hash and branch should be written in history file now.  For CESM coupled version, only model version is written.
