### ISSUE TITLE
Test data link broken

### ISSUE THREAD

**Issue by pmodi7** [ESCOMP/mizuRoute#338]
Hi there, 

The test data link seems to be broken. Is there a new link? If so, how can I get it?

Thanks,
Parth

**Comment by nmizukami** [comment]
Hi,  you can get from google drive here for now (I lost the data host place somehow....).  https://drive.google.com/file/d/1wZfEktgjDyMQLQ9K7As-cn76u-Db_eI3/view?usp=share_link

**Comment by pmodi7** [comment]
Thank you for sharing the link!

Parth

**Comment by nmizukami** [comment]
I will close this
