### ISSUE TITLE
Error in control file for running with CESM

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#372]
The list of CESM tests is failing with ctsm5.1.dev114 and hash 71d4928273dab4e841a1116da72fc70e9e54691a.

One such test is: SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default

the cesm.log is filled with this:

```
-1: 1832	 1832	   32	yes	 r10i1n33    	   32
-1: 1833	 1833	   33	yes	 r10i1n33    	   33
-1: 1834	 1834	   34	yes	 r10i1n33    	   34
-1: 1835	 1835	   35	yes	 r10i1n33    	   35
459:MPT ERROR: Rank 459(g:459) is aborting with error code 1.
459:	Process ID: 64112, Host: r10i5n2, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
459:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
459:
459:MPT: --------stack traceback-------
512:MPT ERROR: Rank 512(g:512) is aborting with error code 1.
512:	Process ID: 52546, Host: r10i5n9, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
512:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
512:
512:MPT: --------stack traceback-------
114:MPT ERROR: Rank 114(g:114) is aborting with error code 1.
114:	Process ID: 36340, Host: r10i1n18, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
114:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
114:
114:MPT: --------stack traceback-------
299:MPT ERROR: Rank 299(g:299) is aborting with error code 1.
299:	Process ID: 13888, Host: r10i4n3, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
299:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
299:
299:MPT: --------stack traceback-------
542:MPT ERROR: Rank 542(g:542) is aborting with error code 1.
542:	Process ID: 38461, Host: r10i4n32, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
```

Last thing in the rof.log file is the read of the control file:

```
---- read control file --- 
 <case_name> --> SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k
 <route_opt> --> 1
 <doesBasinRoute> --> 1
 <is_flux_wm> --> T
 <fname_state_in> --> empty
 <newFileFrequency> --> monthly
 <ancil_dir> --> /glade/p/cesmdata/cseg/inputdata/rof/mizuRoute/ancillary_data/
 <input_dir> --> /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/run/
 <output_dir> --> ./
 <fname_ntopOld> --> ntopo_HDMA_lake_mz_Global_cdf5_fill_reorder_c20221130.nc
 <dname_sseg> --> n
 <dname_nhru> --> n
 <fname_ntopNew> --> UPDATED_NTOPO_NC
 <units_qsim> --> mm/s
 <varname_area> --> area
 <varname_length> --> length
 <varname_slope> --> slope
 <varname_HRUid> --> ID
 <varname_hruSegId> --> ID
 <varname_segId> --> ID
 <varname_downSegId> --> ID_next
 <varname_pfafCode> --> PFAF
 <hydGeometryOption> --> 1
 <topoNetworkOption> --> 1
 <computeReachList> --> 1
 <is_lake_sim> --> T
 <varname_D03_MaxStorage> --> S_max
 <varname_D03_Coefficient> --> Coeff
 <varname_D03_Power> --> power
 <varname_islake> --> lake
 <varname_lakeModelType> --> lake_type
 <param_nml> --> mizuRoute_in
 <basRunoff> --> T
 <instRunoff> --> F
 <dlayRunoff> --> F
 <sumUpstreamRunoff> --> F
 <KWTroutedRunoff> --> T
 <IRFroutedRunoff> --> T
 <MCroutedRunoff> --> T
 <KWroutedRunoff> --> T
 <DWroutedRunoff> --> T
 <volume> --> F
```

**Comment by ekluzek** [comment]
I get the same error with 29eb14fa112c611ec60fd6aca85a055c22d799e7. So perhaps this is a problem with CTSM rather than mizuRoute. That hash is what was used with the ctsm5.1.dev095.mizu baselines.

**Comment by nmizukami** [comment]
Hi Erik, the first error I found is SAMPLE-coupled.control (I need to update some of tag name).  I think old code is not also compatible with the control file you are using.    I will update the SAMPLE-coupled.control (so maybe need to update python script)

**Comment by ekluzek** [comment]
So the real question on this is why we don't get the error message for the coupled case. It perhaps shows up in the cesm.log file, but isn't obvious because it shows up earlier than expected in the file. We should look into this more...

**Comment by ekluzek** [comment]
@nmizukami I think the problem on error logging is that mizuRoute has a convention of returning the message to the next higher level. The thing is that returning to the higher level needs to stop at the highest point and the error printed out. This is still being done at the rof_lnd_nuopc.F90 interface level, and that's where it needs to stop.

So all errors at the level of rof_lnd_nuopc should call shr_sys_abort after printing the error. This will probably take a bit of code changes, but it certainly is something we need to do.

**Comment by nmizukami** [comment]
Hi @ekluzek,

I tested with the latest mizuroute (using https://github.com/nmizukami/mizuRoute/tree/cesm-coupling_bugfix) that fixed the control file. I run with debug mode, but not informative error messages in cesm/rof/lnd/med log files

But I get some error message in PET file.  You can look any of PET log file under /glade/scratch/mizukami/SMS_Lm1.f19_f19_rHDMA_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230504_152301_v3kacw/run/

**Comment by ekluzek** [comment]
I added the error check to my branch and it now shows me issues. It's saying that the time-step isn't right, so I think I know how to fix it. The coupling time-step needs to come from CESM so the buildnml might need to be adjusted to work now. What I see now in the rof.log file is...

```
 <IRFvolume> --> F
 <bypass_routing_option> --> direct_in_place
 <qgwl_runoff_option> --> threshold

---- calendar --- 
  calendar will be read from 
  time_unit will be read from 

---- runoff unit --- 
  runoff unit is provided as: mm/s

---- output/simulation time steps --- 
  simulation time step <dt_qsim>:                -9999.0
  history file freqeuncy <newFileFrequency>:  monthly
  history output freqeuncy <outputFrequency>: 1
 ERROR: 
 (rof_comp_nuopc):(InitializeRealize)init_model/read_control/multiple of <dt_qsi
 m> [sec] must be 86400 [sec] (one day)
```

**Comment by nmizukami** [comment]
Ah, ok!  yes,  This check is happening right after reading the control file, and we have not included and set `dt_qsim` (this is copied to `dt` in global variable). 

so do we know coupling time step (is it coming from namelist?) so we can set in the mizuRoute control file?

**Comment by nmizukami** [comment]
For coupling, dt is set [here](https://github.com/ESCOMP/mizuRoute/blob/71d4928273dab4e841a1116da72fc70e9e54691a/route/build/cpl/RtmMod.F90#L121) now. 

Wondering if dt_qsim should be set in control file (independent of coupling_period) and put a similar constrain for dt_qsim based on coupling_period.

**Comment by ekluzek** [comment]
dt_qsim doesn't quite make sense for CESM. But, I suppose it should be set to the coupling period and that could be done. So I'll add that into buildnml and we should be able to get this work.

**Comment by nmizukami** [comment]
I just tried setting dt_qsim in control file manually and it works now. so this was a problem.
