### ISSUE TITLE
Single processor tests failing

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#376]
Single processor tests are failing

```
SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default	  RUN		
SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  RUN
```	

The cesm.log file has:

```
(shr_orb_params) Long at v.e.(rad) =  -3.247250E-02
(shr_orb_params) -----------------------------------------
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable FLUX_WM_MAIN when it is not allocated

Image              PC                Routine            Line        Source
cesm.exe           0000000004A8652F  Unknown               Unknown  Unknown
cesm.exe           0000000003AFC05C  rtmmod_mp_route_r         584  RtmMod.F90
cesm.exe           0000000003AC2849  rof_comp_nuopc_mp         782  rof_comp_nuopc.F90
libesmf.so         00002B78339AA822  _ZNK5ESMCI13Metho         377  ESMCI_MethodTable.C
libesmf.so         00002B78339ABC86  _ZN5ESMCI11Method         563  ESMCI_MethodTable.C
libesmf.so         00002B78339AA1E7  c_esmc_methodtabl         317  ESMCI_MethodTable.C
libesmf.so         00002B7833DD3287  esmf_attachmethod        1287  ESMF_AttachMethods.F90
```

**Comment by ekluzek** [comment]
The problem is that 

comm_ntopo_data

has an if for MultiProcs -- but not an else for the non MultiProcs case. So flux_wm_main doesn't get allocated and it needs to be.

**Comment by nmizukami** [comment]
Hi Erik,  I found the problem.  if `mutiProcs` is false (use of single core), `comm_ntopo_data` is not called (https://github.com/ESCOMP/mizuRoute/blob/7c5a3aebd3136b6edecb42f58cdcc3756d75be5f/route/build/src/init_model_data.f90#L228). so need to allocate FLUX_WM_MAIN there or in RtmMod (the same for basinRunoff_main etc).  

I did tested my quick fix and looks like it is running.   I will pull request this fix later today.

**Comment by nmizukami** [comment]
Hi Erik,  Looks like this PR fixed it, and the same time removed a few hundreds of lines.
