### ISSUE TITLE
Negative runoff for some HRU's for f19_f19_rHDMAlk_mg17

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#384]
Running the test ERS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default

I see that there are some HRU's that show excessively large negative runoff. Is this a mapping problem or improperly sending data with missing values of a large negative number?

This normally causes the simulation to abort, but I changed it so that it would just write information on the issue, and continue running.

```
73: Exceeded negative runoff tolerance: HRU =      1046429  runoff =   -5.0936586515954391E+073
73: Exceeded negative runoff tolerance: HRU =      1001661  runoff =   -5.0936589609450056E+073
73: Exceeded negative runoff tolerance: HRU =      1038550  runoff =   -5.0936589609450056E+073
73: Exceeded negative runoff tolerance: HRU =      1067494  runoff =   -5.0936589609450056E+073
```
The above warnings then appear to repeat for as long as the simulation continues.

**Comment by nmizukami** [comment]
Hi Erik, did you update the code from my repo `cesm-coupling_restartfix` branch? looks like still precp and evap problem.  I just ran SMS_Lm3.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default, and looks ok to me.

**Comment by ekluzek** [comment]
I haven't merged that branch in yet. Once you merge that to cesm-coupling I'll merge it in and try it that way. Good to know that's likely the previous bug.

**Comment by ekluzek** [comment]
This was really a different problem so closing.
