### ISSUE TITLE
Filenames for daily history filenames are off by one from CLM history filenames

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#388]
Daily history files for mizuroute are named differently in mizuRoute than in CLM. Both have the same value for time, but CLM names it based on the day at the end of the interval rather than the beginning. In CLM this only happens for daily files monthly and yearly files are named appropriately. You can argue that CLM is wrong, but CLM also has a long standing history of naming files this way. And if we change it we would also need to change MOSART and RTM and maybe other components (CAM?).

**Comment by ekluzek** [comment]
This ends up being a problem for the ERI tests and cause them to fail when both CLM and mizuRoute output history files.

FAIL ERI_D.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default COMPARE_base_hybrid
FAIL ERI_D.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default COMPARE_base_rest

**Comment by ekluzek** [comment]
We talked about this in the CTSM software group this morning. Since, changing this would have to be coordinated across many components as well as disrupting post processing workflows, we don't want to take this on now for CESM. But it might be a future change that we do across CESM for CESM4 say?

So we should change this at least for cesm-coupling.  Since, this is something that might change in the future and so to not disrupt standalone processing -- maybe the best way to do it is to have it as an option in the control file? Then it can be at the end of the interval for cesm-coupling, but beginning for standalone. And in the future when/if CESM changes again it'll be easy to switch.

**Comment by nmizukami** [comment]
Ok.  thanks for checking with CTSM software group.  Yes, i will implement an option to use either way.

**Comment by ekluzek** [comment]
This was done in #401, and allows it to be either period-start or period-end.
