### ISSUE TITLE
PIO free decomp should not be done each time the file is closed...

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#399]
Running with NAG I get the following error for a dangling pointing when the freedecomp is being called from close_all for closing the NetCDF history files.

In this case the test that I'm doing is:

SMS_D_Mmpi-serial.5x5_amazon_r05.I2000Clm50SpMizGs.izumi_nag.mizuroute-default

> Runtime Error: /fs/cgd/data0/erik/ctsm_worktree/mizuroute/libraries/parallelio/src/flib/piolib_mod.F90, line 1421: Reference to dangling pointer FILE%IOSYSTEM
> Target was RETURNed from procedure PIOLIB_MOD:PIO_OPENFILE
> Program terminated by fatal error
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/libraries/parallelio/src/flib/piolib_mod.F90, line 1421: Error occurred in PIOLIB_MOD:FREEDECOMP_FILE
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/pio_utils.f90, line 366: Called by PIO_UTILS:FREEDECOMP
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/historyFile.f90, line 406: Called by HISTORYFILE:CLEANUP_HRU
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/historyFile.f90, line 391: Called by HISTORYFILE:CLEANUP
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/write_simoutput_pio.f90, line 456: Called by WRITE_SIMOUTPUT_PIO:CLOSE_ALL
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/src/write_simoutput_pio.f90, line 69: Called by WRITE_SIMOUTPUT_PIO:MAIN_NEW_FILE
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/cpl/RtmMod.F90, line 429: Called by RTMMOD:ROUTE_RUN
> /fs/cgd/data0/erik/ctsm_worktree/mizuroute/components/mizuRoute/route/build/cpl/nuopc/rof_comp_nuopc.F90, line 793: Called by ROF_COMP_NUOPC:MODELADVANCE

I thought the first problem was that HistFile%fileStatus wasn't being explicitly set to FALSE. It is in the type declaration, but I wondered if that was always the case. However, simply making sure it's set to FALSE, doesn't fix the problem.

However, not doing the freedecomp each time the file is closed, does allow the test to work.

**Comment by ekluzek** [comment]
So commenting out the freedecomp calls allows it to complete fine:

``` fortran
@@ -403,7 +404,7 @@ SUBROUTINE cleanup_hru(this)
       implicit none
       class(histFile), intent(inout) :: this
 
-      call freeDecomp(this%pioFileDesc, this%ioDescHruFlux)
+      !call freeDecomp(this%pioFileDesc, this%ioDescHruFlux)
 
     END SUBROUTINE cleanup_hru
 
@@ -414,7 +415,7 @@ SUBROUTINE cleanup_rch(this)
       implicit none
       class(histFile), intent(inout) :: this
 
-      call freeDecomp(this%pioFileDesc, this%ioDescRchFlux)
+      !call freeDecomp(this%pioFileDesc, this%ioDescRchFlux)
 
     END SUBROUTINE cleanup_rch
 
```

**Comment by ekluzek** [comment]
We think the order just needs to be reversed so that the cleanup happens after the file is closed, rather than the other way around. This is consistent with PIO examples from @nmizukami and is consistent with the order things happen on creation.

**Comment by ekluzek** [comment]
Adding back the freeDecomp, but doing the close file before cleanup, did NOT work. It's giving me less information, but still dying. So I'm not clear on what to try now...

**Comment by nmizukami** [comment]
I think not cleaning is ok (as long as it is writing correctly).  maybe ask Jim?  Here it is not doing anything complicated. essentially, doing this. 

```
PIO_freedecomp(pioFileDesc, ioDesc)
pio_closefile(pioFileDesc)
```

or 
```
pio_closefile(pioFileDesc)
PIO_freedecomp(pioFileDesc, ioDesc)
```
and this is very similar to pio example. https://github.com/NCAR/ParallelIO/blob/f45ba898bec31e6cd662ac41f43e0cff14f928b2/examples/f03/examplePio.F90#L378
