### ISSUE TITLE
Have time-stamps for "averaged" output history data be middle of interval, but "instantaneous" be end

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#413]
This is important to comply with the latest convention decided in the CESM co-chairs group. time-stamps for history data that is averaged should be the middle of the interval, and time_bounds should be reported as the start and end of the interval. For instantaneous data (so history data output as "daily" with a daily time-step) the time-stamp should be the end of the interval, and time_bounds NOT included in output.

This was decided in co-chairs on 7/24/2023, and we want it to be put in place for all CESM components by end of Summer.

**Comment by nmizukami** [comment]
I can make this happen fairly easily now (see PR #475 for standalone), but for now using average for aggregation of all variables because there is no capability to outputs into multiple output file streams.
