### ISSUE TITLE
Lakes and reservoirs volumes are not initialized with given restart file for cesm-coupling for one core

### ISSUE THREAD

**Issue by ShervanGharari** [ESCOMP/mizuRoute#414]
I am trying to restart lakes and reservoirs with `cesm-coupling` branch. I need to run the simulation on one core. I noticed when called on one core, the lakes and reservoirs volumes start from zero, however, when more cores are used the lakes and reservoirs are initialized correctly.
I would appreciate it if this issue can be resolved. I need the capability of single-core computation for testing many lake configurations.
In case there is any configuration that I am missing to simulate `cesm-coupling` on one core please let me know.
Thank you in advance.

**Comment by ekluzek** [comment]
This may be related to #390

**Comment by nmizukami** [comment]
> This may be related to #390

Yes, that is what comes to my mind. I will look into this later today.

**Comment by ShervanGharari** [comment]
@nmizukami Thank you very much Naoki for your prompt handling of this issue.
I believe you have tested the code before merging it. I'll give it another test with my setup on Graham and upon success will close this issue.
Thank you very much again!

**Comment by nmizukami** [comment]
Yes, I did test, but please test too, and let me know!

**Comment by ShervanGharari** [comment]
I have tested and it seems in both cases, with one and two cores, the lakes are restarted as they should be.
Thank you very much both.
I close this issue!
