### ISSUE TITLE
Error while compiling using make file

### ISSUE THREAD

**Issue by PrateekSharma99** [ESCOMP/mizuRoute#444]
Good Afternoon, My name is Prateek Sharma, a PhD student from IIT Delhi, India. While setting up my mizuRoute model, 
I am getting the following error while compiling the code :
(envi) [cez218605@chas006 ~/merra2_run/mizuRoute/mizuRoute-main/route/build]
$ make
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
gfortran -O3 -fmax-errors=0 -ffree-line-length-none -fopenmp -cpp -DVERSION=\"\" -DBRANCH=\"\" -DHASH=\"\"  /home/civil/phd/cez218605/merra2_                                                    run/mizuRoute/mizuRoute-main/routebuild/src/nrtype.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/nr_utili                                                    ty.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/ascii_util.f90  /home/civil/phd/cez218605/merra2_run/miz                                                    uRoute/mizuRoute-main/routebuild/src/ncio_utils.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/gamma_func.                                                    f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/public_var.f90  /home/civil/phd/cez218605/merra2_run/mizuRo                                                    ute/mizuRoute-main/routebuild/src/dataTypes.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/var_lookup.f90                                                      /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/time_utils.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/                                                    mizuRoute-main/routebuild/src/datetime_data.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/csv_data.f90  /                                                    home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/gageMeta_data.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute                                                    /mizuRoute-main/routebuild/src/obs_data.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/globalData.f90  /ho                                                    me/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/popMetadat.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizu                                                    Route-main/routebuild/src/allocation.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/network_topo.f90  /hom                                                    e/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/process_param.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mi                                                    zuRoute-main/routebuild/src/process_ntopo.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/pfafstetter.f90                                                      /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/domain_decomposition.f90  /home/civil/phd/cez218605/merra2_run/m                                                    izuRoute/mizuRoute-main/routebuild/src/remap.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_control.f                                                    90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_param.f90  /home/civil/phd/cez218605/merra2_run/mizuRou                                                    te/mizuRoute-main/routebuild/src/read_streamSeg.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/write_strea                                                    mSeg.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_runoff.f90  /home/civil/phd/cez218605/merra2_run/                                                    mizuRoute/mizuRoute-main/routebuild/src/get_basin_runoff.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/re                                                    ad_remap.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_restart.f90  /home/civil/phd/cez218605/merra2                                                    _run/mizuRoute/mizuRoute-main/routebuild/src/write_restart.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/                                                    write_simoutput.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/model_finalize.f90  /home/civil/phd/cez2186                                                    05/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/data_assimilation.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/ro                                                    utebuild/src/accum_runoff.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/basinUH.f90  /home/civil/phd/cez2                                                    18605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/irf_route.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebu                                                    ild/src/kwt_route.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/dfw_route.f90  /home/civil/phd/cez218605/                                                    merra2_run/mizuRoute/mizuRoute-main/routebuild/src/kw_route.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src                                                    /mc_route.f90  /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/main_route.f90  /home/civil/phd/cez218605/merra2_                                                    run/mizuRoute/mizuRoute-main/routebuild/src/model_setup.f90 /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/rout                                                    e_runoff.f90 \
-Wl,-rpath,~/anaconda3/envs/envi/bin//lib -L~/anaconda3/envs/envi/bin//lib -lnetcdff -lnetcdf -I~/anaconda3/envs/envi/bin//include -o route_r                                                    unoff
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/nrtype.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/nr_utility.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/ascii_util.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/ncio_utils.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/gamma_func.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/public_var.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/dataTypes.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/var_lookup.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/time_utils.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/datetime_data.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/csv_data.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/gageMeta_data.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/obs_data.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/globalData.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/popMetadat.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/allocation.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/network_topo.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/process_param.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/process_ntopo.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/pfafstetter.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/domain_decomposition.f90: No such file or direc                                                    tory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/remap.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_control.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_param.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_streamSeg.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/write_streamSeg.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_runoff.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/get_basin_runoff.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_remap.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/read_restart.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/write_restart.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/write_simoutput.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/model_finalize.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/data_assimilation.f90: No such file or director                                                    y
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/accum_runoff.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/basinUH.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/irf_route.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/kwt_route.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/dfw_route.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/kw_route.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/mc_route.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/main_route.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/model_setup.f90: No such file or directory
gfortran: error: /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src/route_runoff.f90: No such file or directory
make: *** [compile] Error 1

![image](https://github.com/ESCOMP/mizuRoute/assets/89891132/df16c83e-adba-4e12-ad2b-f3aafc11202c)
This is the make file
Can anyone guide me through.

**Comment by SoldeMexico** [comment]
Good Morning, My name is Matias Moreno a student from Universidad Diego Portales, Chile. i am getting the same error while compiling the code. How did you solve it?

Beforehand thank you very much.

**Comment by nmizukami** [comment]
if you get the same compiling error, your path to source code (under route/build/src/) in makefile is wrong. The above case, the path specified in F_MASTER is missing`/` at the end.  

If you try locating by typing `ls /home/civil/phd/cez218605/merra2_run/mizuRoute/mizuRoute-main/routebuild/src`,  are you able to see the files? or you get message something like saying directory does not exist?

**Comment by SoldeMexico** [comment]
Thanks for the quick response, I receive the message that the directory does not exist.

**Comment by SoldeMexico** [comment]
In the Bin folder, an executable was created that delivers the message "FATAL ERROR: need to supply name of the control file as a command-line argument" as indicated in the installation document.

I really appreciate your quick help.
