### ISSUE TITLE
Error in Test Case

### ISSUE THREAD

**Issue by PrateekSharma99** [ESCOMP/mizuRoute#445]
While running my test case 1, I am facing the following error that is coming in the output log file.

**---- read control file --- 
---- read control file --- 
 <ancil_dir> --> ./ancillary_data/
 <input_dir> --> ./input/
 <output_dir> --> ./output/
 <case_name> --> case1
---- read control file --- 
 <ancil_dir> --> ./ancillary_data/
 <sim_start> --> 1950-1-1 12:00:00
 <sim_end> --> 1950-12-31 12:00:00
 <restart_write> --> monthly
 <newFileFrequency> --> single
 <outputFrequency> --> daily
 <ancil_dir> --> ./ancillary_data/
 <input_dir> --> ./input/
 <output_dir> --> ./output/
 <case_name> --> case1
 FATAL ERROR: init_model/read_control/unexpected text in control file provided: 
 <outputFrequency> (note strings in control file must match the variable names i
 n public_var.f90)
 <input_dir> --> ./input/
 <output_dir> --> ./output/
 <case_name> --> case1
 <sim_start> --> 1950-1-1 12:00:00
 <sim_end> --> 1950-12-31 12:00:00
 <restart_write> --> monthly
 <newFileFrequency> --> single
 <outputFrequency> --> daily
 <sim_start> --> 1950-1-1 12:00:00
 <sim_end> --> 1950-12-31 12:00:00
 <restart_write> --> monthly
 <newFileFrequency> --> single
 <outputFrequency> --> daily
 FATAL ERROR: init_model/read_control/unexpected text in control file provided: 
---- read control file --- 
 <ancil_dir> --> ./ancillary_data/
 FATAL ERROR: init_model/read_control/unexpected text in control file provided: 
 <outputFrequency> (note strings in control file must match the variable names i
 n public_var.f90)
 <input_dir> --> ./input/
 <outputFrequency> (note strings in control file must match the variable names i
 n public_var.f90)
 <output_dir> --> ./output/
 <case_name> --> case1
 <sim_start> --> 1950-1-1 12:00:00
 <sim_end> --> 1950-12-31 12:00:00
 <restart_write> --> monthly
 <newFileFrequency> --> single
 <outputFrequency> --> daily
 FATAL ERROR: init_model/read_control/unexpected text in control file provided: 
 <outputFrequency> (note strings in control file must match the variable names i
 n public_var.f90)**
 
 I am not able to understand why this is coming up.

**Comment by nmizukami** [comment]
I believe your setting file has some lines **NOT** starting `<tag_name>`, or `!`  
please look at this https://mizuroute.readthedocs.io/en/latest/Control_file.html (especially the beginning of this page to try to understand some of rules in the setting

**Comment by PrateekSharma99** [comment]
Hi @nmizukami. Thankyou for replying. I rechecked my test case setting file. I am also attaching the test case setting, the output, and the public variable list here. 
From the link you shared, I found that I have all the required data in the test case file. I am currently rechecking for any missed data. Please look into it once. 
[https://drive.google.com/drive/folders/1VyPtH1fVHfXRb_6roKHqOSQd0uCRkbyp?usp=sharing](FILES)

**Comment by nmizukami** [comment]
Sorry, but the link to google drive does not look correct (when i hover the link).  Can you directly post your setting file here? maybe format it to the code (highlight the posted text and click on `<>`

**Comment by PrateekSharma99** [comment]
Sure here are the files. 
![image](https://github.com/ESCOMP/mizuRoute/assets/89891132/a94edbde-65e6-4c8e-a094-22bc17e17732)

![image](https://github.com/ESCOMP/mizuRoute/assets/89891132/b7ff3ba9-867c-4154-8a17-5325a44fd57a)
[public_varf90.txt](https://github.com/ESCOMP/mizuRoute/files/13434062/public_varf90.txt)

**Comment by PrateekSharma99** [comment]
The issue has been resolved. Thankyou @nmizukami 
It was a file path issue on my end.

**Comment by PrateekSharma99** [comment]
![image](https://github.com/ESCOMP/mizuRoute/assets/89891132/7f8b91fc-f734-494d-80ec-1b801fbb2469)
While using a global dataset provided by Inne Vanderkelen, I encountered the following error. 

 FATAL ERROR: init_model/read_control/unexpected text in control file provided: 
 <is_lake_sim> (note strings in control file must match the variable names in p
 ublic_var.f90)
 FATAL ERROR: init_model/read_control/unexpected text in control file provided: 
 <is_lake_sim> (note strings in control file must match the variable names in p
 ublic_var.f90)

I have certain doubts since public_var.f90 is already an existing file for the parameters when I compiled my model, how come some variable names are missing in that file? Do I add parameters in that file or is there something that I am missing?

**Comment by nmizukami** [comment]
`<is_lake_sim>` looks ok in the control file. `<lake_model_D3>` and `<lake_model_H06>` are obsolete (they are still in public_var.f90, but looks like forgot to remove them) and you can remove them from the control file.  The types of the lake models now need to be specified in river-lake network netcdf.  Inne's data may be old now, and I can try to find some example that works with the latest code.  

That been said, the error is generated while reading control file (not from network netcdf).  are you able to post your control file somewhere so I can retrieve it and look with my text editor.

**Comment by PrateekSharma99** [comment]
[controlfile.txt](https://github.com/ESCOMP/mizuRoute/files/13516363/controlfile.txt)
[public_varf90.txt](https://github.com/ESCOMP/mizuRoute/files/13516364/public_varf90.txt)
These are the control file and the

**Comment by PrateekSharma99** [comment]
Thank you. I tried the testCase V2.0 but it did not require the cesm-coupling branch. I wanted to use the cesm-coupling branch because I wanted to work on lakes. Also, I use a high-performance computing system and I don't have system admin.

**Comment by nmizukami** [comment]
I believe this thread went to the off-line (i.e., email).
