### ISSUE TITLE
Upstream inflow values for each segment in output files

### ISSUE THREAD

**Issue by ShervanGharari** [ESCOMP/mizuRoute#454]
It is desirable to provide the capability for users to output the upstream inflow to each segment (for each routing scheme) in the output files. This eliminates the need to calculate the upstream contribution to each segment outside mizuRoute. It also becomes handy for checking lakes and reservoirs' water balance/models outside of mizuRoute for which there might be tens of upstream segments. Let me know if I can assist and thank you in advance.

**Comment by nmizukami** [comment]
I think this works now. so close this
