### ISSUE TITLE
Create new global HDMA-lake river input data including reservoir operation

### ISSUE THREAD

**Issue by nmizukami** [ESCOMP/mizuRoute#476]
I got the data from Inne and need to examine and put her data into current HDMA-lake river network (`/glade/campaign/cgd/tss/people/mizukami/mizuRoute_data/cesm_mizuRoute/ancillary_data/Network_topology_HDMA_HydroLake_v3_cdf5.nc`)

and then test with CTSM

**Comment by nmizukami** [comment]
it is `/glade/campaign/cgd/tss/people/mizukami/mizuRoute_data/cesm_mizuRoute/ancillary_data/Network_topology_HDMA_HydroLake_v4_cdf5.nc`

**Comment by ekluzek** [comment]
Thing left to do is to move it to the standard place.

Also we'll need to have a way to control whether reservoir is on or off.
